config/routes.rb
Rails.application.routes.draw do
  resources :holidays
  resources :comments
  resources :photos
  resources :users


  root :to => 'holidays#index'              # Replace this with whatever you want your root_path to be.
                                        # This path is where unauthorized users will be redirected_to.
  get '/login' => 'session#new'         # This will be our sign-in page.
  post '/login' => 'session#create'     # This will be the path to which the sign-in form is posted
  delete '/login' => 'session#destroy'  # This will be the path users use to log-out.
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id         :bigint(8)        not null, primary key
#  created_at :datetime         not null
#  user_id    :integer
#  photo_id   :integer
#  message    :string
#  updated_at :datetime         not null
#

class Comment < ApplicationRecord
  belongs_to :photo
  belongs_to :user
end

app/models/holiday.rb
# == Schema Information
#
# Table name: holidays
#
#  id         :bigint(8)        not null, primary key
#  title      :string
#  created_at :datetime         not null
#  user_id    :integer
#  updated_at :datetime         not null
#

class Holiday < ApplicationRecord
    belongs_to :user, :optional => true
end

app/models/photo.rb
# == Schema Information
#
# Table name: photos
#
#  id         :bigint(8)        not null, primary key
#  created_at :datetime         not null
#  user_id    :integer
#  holiday_id :integer
#  image_url  :string
#  updated_at :datetime         not null
#

class Photo < ApplicationRecord
  belongs_to :holiday
  # belongs_to :user
  has_many :comments
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint(8)        not null, primary key
#  email           :text
#  name            :text
#  password_digest :text
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ApplicationRecord
  has_many :holidays
  has_many :photos
  has_many :comments
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    # TODO if there is a session ID, but it doesn't match a user object
    # delete the session id
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to '/login' unless current_user
  end


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authorize

  def create

    # we create a comment with saved photo
    comment = Comment.new
    comment.user_id = @current_user.id
    comment.message = params[:comment][:message]
    comment.photo_id = params[:comment][:photo_id]
    comment.save

    redirect_back :fallback_location => root_path # GET the show page
  end

  def destroy
    comment = Comment.find params[:id]
    holiday = comment.photo.holiday
    comment.destroy
    flash[:success] = "Comment Deleted!"
    redirect_to holiday
  end

  private
  def comment_params
    params.require(:comment).permit(:message, :user_id, :holiday_id)
  end
end

app/controllers/holidays_controller.rb
class HolidaysController < ApplicationController
    before_action :authorize
  def index
    @holidays = Holiday.all.order(:created_at)
  end

  def new
      @holiday = Holiday.new
  end

  def show
      @holiday = Holiday.find params[:id]
  end

  def edit
      @holiday = Holiday.find params[:id]
      unless @current_user.holidays.include? @holiday
        redirect_to root_path
      else
        render :edit
      end
  end

  def update
    holiday = Holiday.find params[:id]
    holiday.update holiday_params
    redirect_to holiday
  end

  def create
    holiday = Holiday.create holiday_params
    current_user.holidays << holiday
    flash[:success] =  "Holiday Created!"
    redirect_to holiday # GET the show page
  end

  def destroy
    holiday = Holiday.find params[:id]
    holiday.destroy if @current_user.holidays.include? holiday
      flash[:success] =  "Holiday Deleted!"
    redirect_to holidays_path
  end

# Strong params: create a whitelist of permitted parameters
private
def holiday_params
  params.require(:holiday).permit(:title, :user_id, :location, :latitude, :longitude)
end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :authorize

  def show
    @photo = Photo.find params[:id]
  end

  def create
    # First we save the new Photo
    photo = Photo.create photo_params

    # Second we create a comment with saved photo
    comment = Comment.new
    comment.user_id = current_user.id
    comment.message = params[:message]
    comment.photo_id = photo.id
    comment.save

    redirect_to photo.holiday
  end

  def destroy
    # Load the photo using the ID from the URL
    photo = Photo.find params[:id]
    # Make a variable called holiday which is the holiday that
    # the photo belongs to
    holiday = photo.holiday
    # Destroy the photo
    photo.destroy
    # Redirect back to the holiday show page
    redirect_to holiday
  end

  private
  def photo_params
    params.require(:photo).permit(:image_url, :user_id, :holiday_id)
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController


  def new
  # This is the action for user login. The view will have the login form template.
  end

  def create
  # This is the action to which the login form post request is posted. It will add the user's id to the session hash, which will be used for authentication and authorization throughout the session.
    user = User.find_by :email => params[:email]
    if user.present? && user.authenticate(params[:password])
      # If a user record with the entered in the form is present AND the user is authenticated (using bcrypt's authenticate method and the password entered in the form), store their id in the session hash and redirect them to the root path.
      session[:user_id] = user.id
      flash[:notice] = "Welcome back #{user.name}"
      redirect_to root_path
    else
      # If the user cannot be authenticated, redirect them to the login_path.
      flash[:error] = "Sorry, you did not enter valid credentials"
      redirect_to login_path
    end
  end

  # This is the action to which the user sign-out delete request is posted.
  def destroy
    session[:user_id] = nil
    flash[:notice] = "You have logged out."
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Thanks for joining #{@user.name}"
      redirect_to root_path # Redirect to home if the account is valid
    else
      render :new # Let them retry the form again
    end
  end

  private
  def user_params
    params.require(:user).permit(:email, :name, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/holidays_helper.rb
module HolidaysHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/holidays/_edit.html.erb
<%= form_for @holiday do |f| %>
  <div class="container">
    <div class="row">
      <div class="col-12 col-md-6 mx-auto">
        <h1 class="text-center text-white">Update a Holiday</h1>
      </div>
    </div>
    <div class="row">
      <div class="col-12 col-md-6 mx-auto text-white">
        <%= f.label :title %>
        <%= f.text_field :title, :autofocus => true %>
      </div>
    </div>
    <div class="row">
      <div class="col-12 col-md-6 mx-auto text-white">
        <%= f.label :location %>
        <%= f.text_field :location %>
      </div>
    </div>
    <div class="row">
      <div class="col-12 col-md-6 mx-auto text-white">
        <%= f.label :latitude %>
        <%= f.text_field :latitude, class: "form-control" %>
      </div>
    </div>
    <div class="row">
      <div class="col-12 col-md-6 mx-auto text-white">
        <%= f.label :longitude %>
        <%= f.text_field :longitude, class: "form-control" %>
      </div>
    </div>
    <div class="row">
      <div class="col-12 col-md-6 mx-auto py-2">
        <%= submit_tag "Update", class: "btn btn-warning btn-block" %>
      </div>
    </div>
  </div>
<% end %>

app/views/holidays/create.html.erb
<h1>Holidays#create</h1>
<p>Find me in app/views/holidays/create.html.erb</p>

app/views/holidays/destroy.html.erb
<h1>Holidays#destroy</h1>
<p>Find me in app/views/holidays/destroy.html.erb</p>

app/views/holidays/edit.html.erb
<%= render :partial => 'edit' %>

app/views/holidays/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
      <h1 class="text-center text-white p-3 display-3" >All Holidays</h1>
    </div>



      <% @holidays.each do |holiday| %>
        <div class="col-12 col-md-6 col-lg-4 pb-2">
              <p class="bg-light p-2 m-0 h4"><%= link_to holiday.title, holiday %> (<span class="h5"><%= holiday.location %></span>)</p>

          <% if holiday.photos.first.present? %>
            <a href="<%= url_for holiday %>"><img src="<%= holiday.photos.first.image_url %>" class="img-thumbnail img-fluid" alt="<%=holiday.title %>"></a>
          <% else %>
          <p class="bg-light m-0">  No photos uploaded.</p>
          <% end %>



          <!-- <img class="img-fluid img-thumbnail" src="https://maps.googleapis.com/maps/api/staticmap?center=<%= holiday.location %>&zoom=6&size=600x300&maptype=roadmap&key=AIzaSyC1EK8UHAZEehu3sPvGKAinKLGF3TTNkIE"> -->
          <div class="text-center">
              <iframe width="350" height="300" src="https://maps.tilehosting.com/styles/basic/?key=SrArxJQiLFbJOqk6KVoH#10.17/<%= holiday.latitude %>/<%= holiday.longitude %>/0/60"></iframe>
            </div>


          <p class="bg-light p-2">
            Created by <i><%= holiday.user.name %></i>
            on <i><%= holiday.created_at.strftime("%Y-%m-%d") %></i>,
            at <i><%= holiday.created_at.strftime("%I:%M%p") %></i>
          </p>

        </div>
      <% end %>



    </div>
  </div>
</div>

app/views/holidays/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 col-md-6 mx-auto">
      <h1 class="text-white">New Holiday</h1>
    </div>
  </div>
</div>

<%= form_for @holiday do |f| %>
  <div class="container">
    <div class="row">
      <div class="col-12 col-md-6 mx-auto text-white">
        <%= f.label :title %>
        <%= f.text_field :title, :autofocus => true, class: "form-control" %>
      </div>
    </div>
    <div class="row">
      <div class="col-12 col-md-6 mx-auto text-white">
        <%= f.label :location %>
        <%= f.text_field :location, class: "form-control" %>
      </div>
    </div>
    <div class="row">
      <div class="col-12 col-md-6 mx-auto text-white">
        <%= f.label :latitude %>
        <%= f.text_field :latitude, class: "form-control" %>
      </div>
    </div>
    <div class="row">
      <div class="col-12 col-md-6 mx-auto text-white">
        <%= f.label :longitude %>
        <%= f.text_field :longitude, class: "form-control" %>
      </div>
    </div>
    <div class="row">
      <div class="col-12 col-md-6 mx-auto py-2">
        <%= submit_tag "Create Holiday", class: "btn btn-success btn-block" %>
      </div>
    </div>
  </div>
<% end %>

app/views/holidays/show.html.erb
<%= form_for Photo.new do |f| %>
  <div class="container">
    <div class="row">
      <div class="col-12 mx-auto">
        <%= link_to "Go Back", holidays_path, class: 'btn btn-sm btn-info' %>

        <h1 class="text-white display-3"><strong><%= @holiday.title %></strong></h1>

              <ul class="nav justify-content-end mx-2">

            <% if @holiday.user.id == @current_user.id %>
          <li class="nav-item">
            <%= link_to "Edit Holiday", edit_holiday_path(@holiday), class: "btn btn-sm btn-warning"  %>

          </li>
          <li class="nav-item">
            <%= link_to "Delete Holiday", holiday_path(@holiday), :method => 'delete', :data => { :confirm => 'Are you sure?' }, class: "btn btn-sm btn-danger"  %>

          </li>
          <% end %>

        </ul>
      </div>
    </div>
      <div class="row">
        <div class="col-12 mx-auto text-white h4">
          Created by <i><%= @holiday.user.name %></i>
          on <i><%= @holiday.created_at.strftime("%Y-%m-%d") %></i>,
          at <i><%= @holiday.created_at.strftime("%I:%M%p") %></i>
          <!-- <img class="img-fluid img-thumbnail" src="https://maps.googleapis.com/maps/api/staticmap?center=<%= @holiday.location %>&zoom=6&size=600x300&maptype=roadmap&key=AIzaSyC1EK8UHAZEehu3sPvGKAinKLGF3TTNkIE"> -->
          <div class="text-center">
              <iframe width="500" height="300" src="https://maps.tilehosting.com/styles/basic/?key=SrArxJQiLFbJOqk6KVoH#10.17/<%= @holiday.latitude %>/<%= @holiday.longitude %>/0/60"></iframe>
            </div>
        </div>
      </div>


      <% if @holiday.user.id == @current_user.id %>
        <div class="row border mb-2 bg-light rounded">



          <div class="col-12 col-lg-6 mx-auto">
            <%= f.label :image_url %>
            <%= f.url_field :image_url, :autofocus => true, class: "form-control" %>
          </div>
          <div class="col-12 col-lg-6">
              <!-- This will be used to create the first comment on the photo -->
              <!-- The "message" field does not exist in the Photo model, it -->
              <!-- only exists in the Comment model. After we save the new -->
              <!-- Photo in the PhotosController (create action) we then  -->
              <!-- need to create a Comment, assign it the photo_id of the  -->
              <!-- photo we just created and save it with the message below. -->
              <label>Message</label>
              <textarea class="form-control "name="message"></textarea>
          </div>
          <div class="col-12 py-2 mx-auto">
            <!-- A Photo 'belongs to' a Holiday. So when we have a form for -->
            <!-- creating a Photo, we have to specify which holiday it will  -->
            <!-- belong to. Because we are already on the 'show' page for the -->
            <!-- holiday, we know that the holiday_id should be the ID of the -->
            <!-- holiday that we are currently looking at. -->
            <%= f.hidden_field :holiday_id, :value => @holiday.id %>
            <%= f.submit "Add Photo", class: "btn btn-success btn-block"%>
          </div>
        </div>
      </div>
    <% end %>
<% end %>

<div class="container">
  <div class="row">
    <% @holiday.photos.each do |photo| %>
      <div class="col-12 col-md-6 mx-auto">
        <div class="card">
          <a href="<%= url_for photo %>"><img class="card-img-top" src="<%= photo.image_url %>"></a>
            <div class="card-body">
              <% if @holiday.user.id == @current_user.id %>
                <%= link_to "Delete Photo", photo_path(photo), :method => 'delete', :data => { :confirm => 'Are you sure?' }, class: "btn btn-sm btn-danger float-right"  %>
              <% end %>

              <% photo.comments.each do |comment| %>
                <h5 class="card-title"><strong><%= comment.user.name %> says:</strong></h5>
                <p class="card-text"><%= comment.message %></p>
                <% if @holiday.user.id == @current_user.id %>
                  <%= link_to "Delete Comment", comment_path(comment), :method => 'delete', :data => { :confirm => 'Are you sure?' }, class: "btn btn-sm btn-warning"  %>
                <% elsif comment.user.id == @current_user.id %>
                  <%= link_to "Delete Comment", comment_path(comment), :method => 'delete', :data => { :confirm => 'Are you sure?' }, class: "btn btn-sm btn-warning"  %>
                <% end %>
              <% end %>
              <%= form_for Comment.new do |f| %>
                <%= f.label :message, "New Comment" %>
                <%= f.text_field :message, :autofocus => true, class: "form-control" %>
                <%= f.hidden_field :holiday_id, :value => @holiday.id %>
                <%= f.hidden_field :photo_id, :value => photo.id %>
                <button type="submit" class="my-2 btn btn-block btn-success">Add Comment</button>
              <% end %>
            </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/holidays/update.html.erb
<h1>Holidays#update</h1>
<p>Find me in app/views/holidays/update.html.erb</p>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>HolidayApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/css/bootstrap.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-sm navbar-dark text-white bg-dark" style="background-color:#000066 !important;">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <%= link_to 'All Holidays', holidays_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'New Holiday', new_holiday_path, class: "nav-link" %>
          </li>
        </ul>
        <ul class="navbar-nav">
          <% if @current_user.present? %>
            <li class="nav-item">
              <%= link_to "Log out #{ @current_user.name }", login_path, :method => 'delete', class: "nav-link" %>


            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to new_user_path, class: "nav-link text-white" do %>
                <i class="fas fa-user-plus"></i> Sign Up
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to login_path, class: "nav-link text-white" do %>
                <i class="fas fa-sign-in-alt"></i> Log In
              <% end %>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>

    <div class="container">
      <div class="row my-2">
        <div class="col-12 col-md-6 mx-auto">
          <% if flash[:success] %>
            <div class="alert-success alert">
              <%= flash[:success]%>
            </div>
          <% end %>
          <% if flash[:notice] %>
            <div class="alert-info alert">
              <%= flash[:notice]%>
            </div>
          <% end %>
          <% if flash[:error] %>
            <div class="alert-danger alert">
              <%= flash[:error]%>
            </div>
          <% end %>
        </div>
      </div>
    </div>
    <%= yield %>
    <div class="footer fixed-bottom mt-4 p-2 bg-dark text-white text-center" style="background-color:#000066 !important;">
      Copyright @sonicakes 2018
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/js/bootstrap.min.js"></script>
  </body>
</html>

app/views/photos/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
      <div class="card">
        <div class="card-body">
          <img class="img-fluid" src="<%= @photo.image_url %>" alt="<%= @photo.holiday.title %>">
          <% @photo.comments.each do |comment| %>
            <b><%= comment.user.name %></b> says:
            <%= comment.message %><br>
          <% end %>
          <%= link_to "Back to #{@photo.holiday.title}", @photo.holiday, :method => :get, class: 'btn btn-info' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/session/new.html.erb
<%= form_tag login_path do %>
  <div class="container">
    <div class="row">
      <div class="col-12 col-md-6 mx-auto">
        <h1 class="text-white">Log In</h1>
      </div>
    </div>
    <div class="row">
      <div class="col-12 col-md-6 mx-auto text-white">
        <%= label_tag :email %>
        <%= email_field_tag :email, "", class: "form-control" %>
      </div>
    </div>
    <div class="row">
      <div class="col-12 col-md-6 mx-auto text-white">
        <%= label_tag :password %>
        <%= password_field_tag :password, "", class: "form-control" %>
      </div>
    </div>
    <div class="row">
      <div class="col-12 col-md-6 mx-auto py-2">
        <%= button_tag type: 'submit', class: "btn btn-primary btn-block", style: "background: #000066;" do %>
          <i class="fas fa-sign-in-alt"></i> Log In!
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<%= form_for @user do |f| %>
  <div class="container">
    <div class="row ">
      <div class="col-12 col-md-6 mx-auto">
        <h1 class="text-white">Sign Up</h1>
      </div>
    </div>

      <% if @user.errors.any? %>
        <div class="row ">
          <div class="col-12 col-md-6 mx-auto">
          <% @user.errors.full_messages.each do |msg| %>
            <p class="alert alert-warning"><%= msg %></li>
          <% end %>
          </div>
        </div>
      <% end %>

      <div class="row ">
        <div class="col-12 col-md-6 mx-auto text-white">
          <%= f.label :email %>
          <%= f.email_field :email, class: "form-control" %>
        </div>
      </div>
      <div class="row">
        <div class="col-12 col-md-6 mx-auto text-white">
          <%= f.label(:name, "User Name")%>
          <%= f.text_field :name, class: "form-control" %>
        </div>
      </div>
      <div class="row">
        <div class="col-12 col-md-6 mx-auto text-white">
          <%= f.label :password %>
          <%= f.password_field :password, class: "form-control" %>
        </div>
      </div>
      <div class="row">
        <div class="col-12 col-md-6 mx-auto text-white">
          <%= f.label :password_confirmation %>
          <%= f.password_field :password_confirmation, class: "form-control" %>
        </div>
      </div>
      <div class="row">
        <div class="col-12 col-md-6 mx-auto py-2">
          <%= f.button '<i class="fas fa-user-plus"></i> Sign Up!'.html_safe, class: "btn btn-primary btn-block", style: "background: #000066;" %>

        </div>
      </div>
  </div>
<% end %>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>